# Generated by Django 3.2 on 2023-01-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_ecommereceorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcommereceOrder',
            new_name='EcommerceOrder',
        ),
    ]
