# Generated by Django 3.2 on 2023-01-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_ecommerceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Block', 'Block')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=100)),
                ('assign_to', models.CharField(max_length=150)),
                ('create_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Inprogress', 'Inprogress'), ('New', 'New'), ('Open', 'Open')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
            ],
        ),
    ]
