# Generated by Django 3.2 on 2023-01-03 09:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_crmcontact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=13),
        ),
    ]
